apiVersion: v1
kind: Service
metadata:
  name: config-clusterip-service
spec:
  selector:
    app: config-app
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
---
kind: Service
apiVersion: v1
metadata:
  name: config-nodeport-service
spec:
  type: NodePort
  selector:
    app: config-app
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-deployment
  labels:
    app: config-app
spec:
  replicas: 6
  selector:
    matchLabels:
      app: config-app
  template:
    metadata:
      labels:
        app: config-app
    spec:
      containers:
      - name: config-app
        image: sebasgarciamo/app-config:mt-2
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: bd-pay-clusterip-service
spec:
  selector:
    app: pay-bd
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: pay-bd-replicaset
  labels:
    app: pay-bd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pay-bd
  template:
    metadata:
      labels:
        app: pay-bd
    spec:
      containers:
      - name: pay-bd
        image: sebasgarciamo/mysql-app-pay:mt-2
        ports:
        - containerPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pay-deployment
  labels:
    app: pay-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pay-app
  template:
    metadata:
      labels:
        app: pay-app
    spec:
      containers:
      - name: pay-app
        image: sebasgarciamo/app-pay:2
        ports:
        - containerPort: 8010
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  labels:
    app: kafka-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-app
  template:
    metadata:
      labels:
        app: kafka-app
    spec:
      containers:
      - name: kafka-app
        image: johnnypark/kafka-zookeeper
        ports:
        - containerPort: 9092
          name: "idk"
        - containerPort: 2181
          name: "idk2"
        env:
          - name: NUM_PARTITIONS
            value: "3"
---
kind: Service
apiVersion: v1
metadata:
  name: kafka-service
spec:
  selector:
   app: kafka-app
  ports:
   - protocol: TCP
     port: 9092
     targetPort: 9092
     name: idk
   - protocol: TCP
     port: 2181
     targetPort: 2181
     name: idk2