apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-deployment
  labels:
    app: invoice-app
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: invoice-app
  template:
    metadata:
      labels:
        app: invoice-app
    spec:
      containers:
      - name: invoice-app
        image: sebasgarciamo/app-invoice:mt-2
        ports:
        - containerPort: 8006
---
apiVersion: v1
kind: Service
metadata:
  name: invoice-app-lb
spec:
  type: LoadBalancer
  selector:
    app: invoice-app
  ports:
    - protocol: TCP
      port: 8006
      targetPort: 8006