apiVersion: v1
kind: Service
metadata:
  name: bd-transaction-clusterip-service
spec:
  selector:
    app: transaction-bd
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: transaction-bd-replicaset
  labels:
    app: transaction-bd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction-bd
  template:
    metadata:
      labels:
        app: transaction-bd
    spec:
      containers:
      - name: transaction-bd
        image: mongo
        ports:
        - containerPort: 27017